### ISSUE TITLE
Content Pack install failed

### ISSUE THREAD

**Issue by ddistler** [seanthegeek/graylog-fortigate-syslog-pipeline#1]
When attempting to install on a new Graylog installation I get the following error:

<img width="2033" alt="image" src="https://github.com/seanthegeek/graylog-fortigate-syslog-pipeline/assets/4342073/0fbd785b-e6a6-4e6a-9c99-7197d177440a">

I had simlar issues with FortiGate syslog content pack. Was able to install Rev 14, Rev 20, then Rev 25. Tried a similar approach for the pipeline content pack and was unsuccessful. I do have the fortigate index setup prior to installation.

**Comment by seanthegeek** [comment]
1.0.5-rev7 will install properly. Before attempting to install it, delete any pipeline rules and pipelines that were created by previous attempts to install it. These will exist even if the content pack failed to fully install. The entire content pack installation will fail if a pipeline rule or pipeline with same name already exists.
